<a href="https://colab.research.google.com/github/oguzhan-bolukbas/Deep_Learning_with_Python/blob/main/Kod_2_1_MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Keras veriseti kümesinden MNIST veriseti içe aktarılır


In [48]:
from keras.datasets import  mnist

In [49]:
# Veri setini eğitim ve sınama olmak üzere iki öbeğe ayırır
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

## Eğitim veriseti incelenir

In [50]:
train_images.shape

(60000, 28, 28)

In [51]:
len(train_labels)

60000

In [52]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

## Sınama veriseti incelenir

In [53]:
test_images.shape

(10000, 28, 28)

In [54]:
len(test_labels)

10000

In [55]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

## Sinir ağı oluşturulur

In [56]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
network.add(layers.Dense(10, activation='softmax'))

## Eniyileme, kayıp fonksiyonu ve metrik eklenir

In [57]:
network.compile(optimizer='rmsprop',  # Ağın veri ile kayba bakarak kendini güncellemesi için
                loss='categorical_crossentropy',  # Ağın kendi performansını gözlemlemesi için
                metrics=['accuracy'])  # Sinir ağı doğruluğa odaklanacak

## Veriseti modelin kullanabileceği şekle dönüştürülür

In [58]:
train_images = train_images.reshape((60000, 28*28))  # Tek boyutlu diziye dönüştürür
train_images = train_images.astype('float32') / 255  # Verileri 0 ile 1 arasına orantılar

test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype('float32') / 255

## Etiketler hazırlanır

In [59]:
print(train_labels.shape)
train_labels

(60000,)


array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [60]:
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [61]:
print(train_labels.shape)
train_labels

(60000, 10)


array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

## Model eğitilir

In [62]:
network.fit(train_images,train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 2s 3ms/step - loss: 0.4302 - accuracy: 0.8728
Epoch 2/5
469/469 [==============================] - 1s 3ms/step - loss: 0.1155 - accuracy: 0.9656
Epoch 3/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0721 - accuracy: 0.9784
Epoch 4/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0497 - accuracy: 0.9845
Epoch 5/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0359 - accuracy: 0.9899


In [63]:
network.fit(train_images,train_labels, epochs=5, batch_size=32)  # Farklı batch_size'lar denenerek farklı sonuçlar elde edilebilir

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0435 - accuracy: 0.9867
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0354 - accuracy: 0.9893
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0290 - accuracy: 0.9918
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0243 - accuracy: 0.9928
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0200 - accuracy: 0.9945


## Test veriseti ile test edilir

In [64]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print("Loss: ", test_loss)
print("Accuracy: ", test_acc)

313/313 [==============================] - 1s 2ms/step - loss: 0.0893 - accuracy: 0.9828
Loss:  0.0893041342496872
Accuracy:  0.9828000068664551
